// Shape of public/cities.json (generated by scripts/sync-cities.mjs).

/** [name, aliases ("|"-separated), region index, lat, lng, zone index]. */
export type CityRow = [string, string, number, number, number, number];

export interface CityData {
  /** IANA time zones. */
  zones: string[];
  /** "CC|State"; index 0 is empty. */
  regions: string[];
  cities: CityRow[];
}
